apply plugin: 'com.android.test'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace 'tech.dongdongbh.mindwtr.macrobenchmark'
    compileSdk 36
    defaultConfig {
        minSdk 29
        targetSdk 36
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
    }
    targetProjectPath = ':app'
    experimentalProperties['android.experimental.self-instrumenting'] = true
    buildTypes {
        release { debuggable = true; signingConfig signingConfigs.debug }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }
}

dependencies {
    implementation 'androidx.benchmark:benchmark-macro-junit4:1.4.1'
    implementation 'androidx.test.ext:junit:1.2.1'
    implementation 'androidx.test:runner:1.6.2'
    implementation 'androidx.test.uiautomator:uiautomator:2.3.0'
}
